TILE_SIZE = 200
TILE_ROW = 3
TILE_COL = 3
TILE_GAP = 10
SCREEN_HEIGHT = ((TILE_SIZE*TILE_ROW)+((TILE_GAP*TILE_ROW)+TILE_GAP))
SCREEN_WIDTH = ((TILE_SIZE*TILE_COL)+((TILE_GAP*TILE_COL)+TILE_GAP))
GRID_NOTPLAYED = 0
GRID_PLAYED_X = 1
GRID_PLAYED_Y = 2
TILE_COLORS = [
    (230,230,230),
    (0,255,0),
    (0,0,255)
]